import { Bell, Building2, Check, KeyRound, Palette, Save, ShieldCheck, SlidersHorizontal } from 'lucide-react';
import { useState } from 'react';
import { Button, DataLabel } from '../components/ui';
import { useCampusFit } from '../data/CampusFitContext';
import { useTenant } from '../data/TenantContext';

export function AdminPage() {
  const { tenant, state } = useTenant();
  const { updateTenant, notify } = useCampusFit();
  const [primaryColor, setPrimaryColor] = useState(state.university.primaryColor);
  const [accentColor, setAccentColor] = useState(state.university.accentColor);
  const [threshold, setThreshold] = useState(state.university.privacyCountThreshold);
  const [grace, setGrace] = useState(state.university.autoCloseGraceMinutes);
  const [authMode, setAuthMode] = useState('demo');
  const [notification, setNotification] = useState('Your CampusFit visit is nearly complete. Still here?');
  const save = () => updateTenant(tenant, (current) => ({ ...current, university: { ...current.university, primaryColor, accentColor, privacyCountThreshold: threshold, autoCloseGraceMinutes: grace } }), 'University settings saved');
  return <div className="page-stack admin-page"><header className="page-header"><div><DataLabel>University administration</DataLabel><h1>Configure CampusFit for {state.university.shortName}.</h1><p>Tenant-scoped branding, privacy, lifecycle, catalogue, and integration settings.</p></div><Button size="large" onClick={save}><Save />Save all settings</Button></header>
    <div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections"><a href="#branding"><Palette />Branding</a><a href="#privacy"><ShieldCheck />Privacy & lifecycle</a><a href="#auth"><KeyRound />Authentication</a><a href="#notifications"><Bell />Notifications</a><a href="#catalogue"><Building2 />Campus catalogue</a></nav><div className="settings-content">
      <section id="branding" className="settings-card"><div className="settings-heading"><span><Palette /></span><div><h2>University branding</h2><p>Applied centrally across shared CampusFit components.</p></div></div><div className="form-grid"><label>Primary colour<span className="color-input"><input type="color" value={primaryColor} onChange={(event) => setPrimaryColor(event.target.value)} /><input value={primaryColor} onChange={(event) => setPrimaryColor(event.target.value)} /></span></label><label>Accent colour<span className="color-input"><input type="color" value={accentColor} onChange={(event) => setAccentColor(event.target.value)} /><input value={accentColor} onChange={(event) => setAccentColor(event.target.value)} /></span></label><label>University name<input value={state.university.name} readOnly /></label><label>Campus email domain<input value={state.university.emailDomain} readOnly /></label></div></section>
      <section id="privacy" className="settings-card"><div className="settings-heading"><span><ShieldCheck /></span><div><h2>Privacy & visit lifecycle</h2><p>Enforced server-side in production.</p></div></div><div className="form-grid"><label>Minimum aggregate count<input type="number" min="3" max="10" value={threshold} onChange={(event) => setThreshold(Number(event.target.value))} /><small>Counts below this value display as “Low activity.”</small></label><label>Auto-close grace period<input type="number" min="10" max="90" value={grace} onChange={(event) => setGrace(Number(event.target.value))} /><small>Minutes after expected visit completion.</small></label></div><div className="settings-assurance"><Check />Public clients receive aggregate views only; individual active visit rows remain restricted.</div></section>
      <section id="auth" className="settings-card"><div className="settings-heading"><span><KeyRound /></span><div><h2>Authentication adapter</h2><p>No real university SSO is connected in this prototype.</p></div></div><label>Configured mode<select value={authMode} onChange={(event) => setAuthMode(event.target.value)}><option value="demo">Demonstration login</option><option value="oidc">OpenID Connect (not connected)</option><option value="saml">SAML (not connected)</option></select></label><div className="integration-state"><span /><p><strong>Demo adapter active</strong><br />Switching this selector does not claim or create a live integration.</p></div></section>
      <section id="notifications" className="settings-card"><div className="settings-heading"><span><Bell /></span><div><h2>Reminder wording</h2><p>Shown near expected workout completion.</p></div></div><label>In-app reminder<textarea rows={3} value={notification} onChange={(event) => setNotification(event.target.value)} /></label></section>
      <section id="catalogue" className="settings-card"><div className="settings-heading"><span><Building2 /></span><div><h2>Campus catalogue</h2><p>Tenant-owned resources available in this demo.</p></div></div><div className="catalogue-stats"><div><strong>{state.facilities.length}</strong><span>Facilities</span></div><div><strong>{state.equipmentTypes.length}</strong><span>Equipment types</span></div><div><strong>10</strong><span>Activities</span></div><div><strong>12</strong><span>Workout focuses</span></div></div><Button variant="secondary" onClick={() => notify('Catalogue review is available through Facilities and Staff tools', 'info')}><SlidersHorizontal />Review catalogue</Button></section>
    </div></div>
  </div>;
}
