import { Bell, Building2, Check, KeyRound, Palette, Save, ShieldCheck, SlidersHorizontal } from 'lucide-react';
import { useState } from 'react';
import { Button, FormMessage, ManagementMetric, ManagementMetricGrid, ManagementPageHeader, ManagementSectionHeader, StatusPill } from '../components/ui';
import { useCampusFit } from '../data/CampusFitContext';
import { useTenant } from '../data/TenantContext';

export function AdminPage() {
  const { tenant, state } = useTenant();
  const { updateTenant, notify } = useCampusFit();
  const [primaryColor, setPrimaryColor] = useState(state.university.primaryColor);
  const [accentColor, setAccentColor] = useState(state.university.accentColor);
  const [threshold, setThreshold] = useState(state.university.privacyCountThreshold);
  const [grace, setGrace] = useState(state.university.autoCloseGraceMinutes);
  const [authMode, setAuthMode] = useState('demo');
  const [notification, setNotification] = useState('Your CampusFit visit is nearly complete. Still here?');
  const colorsValid = /^#[0-9a-f]{6}$/i.test(primaryColor) && /^#[0-9a-f]{6}$/i.test(accentColor);
  const thresholdValid = Number.isInteger(threshold) && threshold >= 3 && threshold <= 10;
  const graceValid = Number.isInteger(grace) && grace >= 10 && grace <= 90;
  const settingsValid = colorsValid && thresholdValid && graceValid;
  const hasChanges = primaryColor !== state.university.primaryColor || accentColor !== state.university.accentColor || threshold !== state.university.privacyCountThreshold || grace !== state.university.autoCloseGraceMinutes;
  const save = () => updateTenant(tenant, (current) => ({ ...current, university: { ...current.university, primaryColor, accentColor, privacyCountThreshold: threshold, autoCloseGraceMinutes: grace } }), 'University settings saved');
  return <div className="page-stack admin-page"><ManagementPageHeader eyebrow="University administration" title={`Configure CampusFit for ${state.university.shortName}`} description="Manage tenant-scoped branding, privacy, lifecycle, catalogue, and integration settings." actions={<><StatusPill level={hasChanges ? 'moderate' : 'completed'}>{hasChanges ? 'Unsaved changes' : 'Settings current'}</StatusPill><Button size="large" onClick={save} disabled={!settingsValid || !hasChanges}><Save />Save university settings</Button></>} />
    <ManagementMetricGrid label="University configuration summary">
      <ManagementMetric icon={<Building2 />} value={state.facilities.length} label="Facilities" note="Tenant-owned recreation locations" />
      <ManagementMetric icon={<ShieldCheck />} value={threshold} label="Privacy threshold" note="Minimum aggregate count" tone="positive" />
      <ManagementMetric icon={<Bell />} value={`${grace} min`} label="Visit grace period" note="Before automatic closure" />
    </ManagementMetricGrid>
    <div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections"><a href="#branding"><Palette />Branding</a><a href="#privacy"><ShieldCheck />Privacy & lifecycle</a><a href="#auth"><KeyRound />Authentication</a><a href="#notifications"><Bell />Notifications</a><a href="#catalogue"><Building2 />Campus catalogue</a></nav><div className="settings-content">
      <section id="branding" className="settings-card"><ManagementSectionHeader icon={<Palette />} title="University branding" description="Applied centrally across shared CampusFit components." /><div className="form-grid"><label>Primary colour<span className="color-input"><input aria-label="Primary colour picker" type="color" value={primaryColor} onChange={(event) => setPrimaryColor(event.target.value)} /><input value={primaryColor} aria-invalid={!/^#[0-9a-f]{6}$/i.test(primaryColor)} aria-describedby="primary-colour-help" onChange={(event) => setPrimaryColor(event.target.value)} /></span><FormMessage id="primary-colour-help" tone={/^#[0-9a-f]{6}$/i.test(primaryColor) ? 'hint' : 'error'}>Use a six-digit hex colour, such as #57068c.</FormMessage></label><label>Accent colour<span className="color-input"><input aria-label="Accent colour picker" type="color" value={accentColor} onChange={(event) => setAccentColor(event.target.value)} /><input value={accentColor} aria-invalid={!/^#[0-9a-f]{6}$/i.test(accentColor)} aria-describedby="accent-colour-help" onChange={(event) => setAccentColor(event.target.value)} /></span><FormMessage id="accent-colour-help" tone={/^#[0-9a-f]{6}$/i.test(accentColor) ? 'hint' : 'error'}>Use a six-digit hex colour for supporting emphasis.</FormMessage></label><label>University name<input value={state.university.name} readOnly /></label><label>Campus email domain<input value={state.university.emailDomain} readOnly /></label></div></section>
      <section id="privacy" className="settings-card"><ManagementSectionHeader icon={<ShieldCheck />} title="Privacy & visit lifecycle" description="Enforced server-side in production." /><div className="form-grid"><label>Minimum aggregate count<input type="number" min="3" max="10" value={threshold} aria-invalid={!thresholdValid} aria-describedby="privacy-threshold-help" onChange={(event) => setThreshold(Number(event.target.value))} /><FormMessage id="privacy-threshold-help" tone={thresholdValid ? 'hint' : 'error'}>{thresholdValid ? 'Counts below this value display as “Low activity.”' : 'Enter a whole number from 3 to 10.'}</FormMessage></label><label>Auto-close grace period<input type="number" min="10" max="90" value={grace} aria-invalid={!graceValid} aria-describedby="grace-period-help" onChange={(event) => setGrace(Number(event.target.value))} /><FormMessage id="grace-period-help" tone={graceValid ? 'hint' : 'error'}>{graceValid ? 'Minutes after expected visit completion.' : 'Enter a whole number from 10 to 90.'}</FormMessage></label></div><div className="settings-assurance"><Check />Public clients receive aggregate views only; individual active visit rows remain restricted.</div></section>
      <section id="auth" className="settings-card"><ManagementSectionHeader icon={<KeyRound />} title="Authentication adapter" description="No real university SSO is connected in this prototype." status={<StatusPill level="unknown">Prototype only</StatusPill>} /><label>Configured mode<select value={authMode} onChange={(event) => setAuthMode(event.target.value)}><option value="demo">Demonstration login</option><option value="oidc">OpenID Connect (not connected)</option><option value="saml">SAML (not connected)</option></select></label><div className="integration-state"><span /><p><strong>Demo adapter active</strong><br />Switching this selector does not claim or create a live integration; it previews configuration only.</p></div></section>
      <section id="notifications" className="settings-card"><ManagementSectionHeader icon={<Bell />} title="Reminder wording" description="Shown near expected workout completion." status={<StatusPill level="unknown">Prototype preview</StatusPill>} /><label>In-app reminder<textarea rows={3} value={notification} onChange={(event) => setNotification(event.target.value)} /></label><FormMessage>This prototype previews reminder copy locally; the university settings action does not publish notifications.</FormMessage></section>
      <section id="catalogue" className="settings-card"><ManagementSectionHeader icon={<Building2 />} title="Campus catalogue" description="Tenant-owned resources available in this demo." /><div className="catalogue-stats"><div><strong>{state.facilities.length}</strong><span>Facilities</span></div><div><strong>{state.equipmentTypes.length}</strong><span>Equipment types</span></div><div><strong>10</strong><span>Activities</span></div><div><strong>12</strong><span>Workout focuses</span></div></div><Button variant="secondary" onClick={() => notify('Catalogue review is available through Facilities and Staff tools', 'info')}><SlidersHorizontal />Review catalogue</Button></section>
    </div></div>
  </div>;
}
